### ISSUE TITLE
Examples don't use development version of ApproximateGPs

### ISSUE THREAD

**Issue by devmotion** [JuliaGaussianProcesses/ApproximateGPs.jl#105]
I didn't see any discussion about this so I assume that https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/pull/99 might have changed it unintentionally and introduced a bug: In contrast to previous behaviour and when e.g. building the documentation, with this PR now examples use the latest compatible released version of ApproximateGPs instead of e.g. the master branch or a PR. So it can happen that examples run fine in a PR but fail as soon as the next release is tagged.

**Comment by st--** [comment]
Woops, yes, definitely an unintentional bug. Thanks for spotting it!

**Comment by st--** [comment]
fixed by #119

**Comment by devmotion** [comment]
That's only a workaround, not a proper fix. The manifest files and package information obtained with the linked PR (which BTW introduced formatting issues and should not have been merged it seems) are not helpful for reproducing the examples. Instead of the development version they should use the corresponding release or commit if run on the master branch.
