### ISSUE TITLE
`SparseVariationalApproximation` breaks with PDMats.jl v0.11.8

### ISSUE THREAD

**Issue by simsurace** [JuliaGaussianProcesses/ApproximateGPs.jl#131]
When running the [example](https://juliagaussianprocesses.github.io/ApproximateGPs.jl/dev/examples/b-classification/), the optimization does not work properly, i.e. the optimal covariance matrix of the sparse approximation remains diagonal.

**Comment by simsurace** [comment]
So I guess ApproximateGPs.jl depends on some internals of PDMats.jl then.

**Comment by devmotion** [comment]
Indeed, it seems SparseVariationalApproximations uses the unexported `PDMats.chol_lower`: https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/blob/dec97855a780cea0ede48fd85b5106722ab9f159/src/SparseVariationalApproximationModule.jl#L12

**Comment by st--** [comment]
> (BTW it also uses some other internals such as https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/blob/master/src/SparseVariationalApproximationModule.jl#L26)

these are actually defined in https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/blob/master/src/utils.jl

**Comment by devmotion** [comment]
Fixed by #133.
