### ISSUE TITLE
Move quadrature to GPLikelihoods

### ISSUE THREAD

**Issue by rossviljoen** [JuliaGaussianProcesses/ApproximateGPs.jl#53]
The various `expected_loglik` methods should really live in [GPLikelihoods.jl](https://github.com/JuliaGaussianProcesses/GPLikelihoods.jl) since they're not at all specific to ApproxGPs.

**Comment by st--** [comment]
I'm happy to make a PR there once #54 is in.
(I also had a few thoughts on how to change it slightly, maybe a good opportunity to discuss at the same time)
