### ISSUE TITLE
Whitening parametrisation

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/ApproximateGPs.jl#60]
In many cases, optimising an `SVGP` model is much easier when parametrising it in the "whitened" representation, i.e. for `L L' = K`, we parametrise `u = f(Z) = L * v` with `v ~ N(0, I)` (such that under the prior, `u ~ N(0, K)` is the same as before). Could maybe make use of PDMats.jl's `whiten`/`unwhiten` functions. Not sure how this would work as a feature _within_ the package, but at the very least it should be fairly straightforward to demonstrate how you would do this "by hand" in one of the notebooks.

**Comment by willtebbutt** [comment]
Agreed -- this parametrisation would be very helpful. Starting with a notebook and then figuring out how it might work inside the package seems good to me. Probably we just need a way inside the `SVGP` to specify which parametrisation we're using so that we can dispatch on that or something.

**Comment by rossviljoen** [comment]
I've also been messing around with MCMC for sparse GPs which uses the same parameterisation - so would be good to figure out a general way of handling it

**Comment by theogf** [comment]
@rossviljoen Do you have an example of this somewhere? Even as a gist?

**Comment by rossviljoen** [comment]
yes, it's an example in the branch `ross/mcmc` of this repo (not sure it actually belongs in this package though?)

**Comment by willtebbutt** [comment]
Am working on doing this at the minute. PR incoming shortly.

**Comment by theogf** [comment]
Hahaha so we are only 3 people working on exactly the same thing :laughing:

**Comment by rossviljoen** [comment]
We'll have to do double blind PR review :laughing:
