### ISSUE TITLE
`SVGP` deprecation not exact

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/ApproximateGPs.jl#88]
`SVGP` simply redirects to `SparseVariationalApproximation`, but the `SVGP` default (and only implementation) was `Centered` representation, whereas `SparseVariationalApproximation` defaults to `NonCentered`. So it was actually a breaking change. Is there some way we can fix this?

_Originally posted by @st-- in https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/pull/64#discussion_r782007833_

**Comment by st--** [comment]
I think it'd be better to remove the `@deprecate` and instead have a stub
```julia
SVGP(args...) = error("`SVGP(...)` is deprecated; use `SparseVariationalApproximation(Centered(), ...)` for retaining previous behaviour, or consider if you want to use NonCentered() [new default] instead.")
```

**Comment by theogf** [comment]
But isn't it an issue now that this is a bug and that should be solved before the next breaking release (your solution is nice but would be breaking

**Comment by st--** [comment]
My solution would be fixing a bug - the change from SVGP to SparseVariationalApproximation was already declared breaking. If anyone is actually using SVGP, and they rely on `@deprecate` preserving the behaviour, their code might give them wrong answers (without realising). An explicit error message that tells them how to fix it would be much preferable, no?

**Comment by devmotion** [comment]
> Moreover, @deprecate as of julia 1.5 doesn't by default print any warnings, so in practice users are likely to miss it.

AFAIK this is on purpose since deprecatipn warmings slow down code massively. Eg, deprecations in a Turing model make it basically impossible to sample with the model if warnings are enabled.

**Comment by st--** [comment]
Actually, the type doesn't get aliased anyways, so doesn't make a difference. See #95. (Though personally I'd still prefer an explicit `error()`!)

**Comment by devmotion** [comment]
`@deprecate_binding` can be used to deprecate types.

**Comment by st--** [comment]
> `@deprecate_binding` can be used to deprecate types.

it doesn't work together with the constructor `@deprecate` though...
