### ISSUE TITLE
RFC: sub-modules for each approximations

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/ApproximateGPs.jl#90]
To have slightly tidier namespaces, and make more explicit which approximations depend on which other packages.
This wouldn't change the exported API of ApproximateGPs.jl, but internal code (such as tests) wanting to access internals would have to e.g. access `ApproximateGPs.Laplace.build_objective` instead of `ApproximateGPs.build_laplace_objective` (actually, I think that would make it neater, to have `ApproximateGPs.<sub_module>.build_objective` instead of multiple build_<some>_objective functions next to each other). What are your thoughts? Any objections?

**Comment by theogf** [comment]
This sounds a bit like a Python solution to me. Can't we just pass the `LaplaceApproximation` object or whatever relevant object to `build_objective` and use multiple dispatch?

**Comment by willtebbutt** [comment]
IIUC @st-- 's suggestion, the point we be to not change the user-facing API, just to tidy up the internals.

I could imagine the usual multiple dispatch solution failing here if it's the case that there's lot of helper functions that are specific to each approximation, for example. e.g. `_prior_kl` in the SparseVariationalApproximation presumably won't get used in the `Laplace` approximation 🤷 

I guess the other question would be: does using submodules gain us anything that name-mangling doesn't, beyond aesthetics when you type `ApproximateGPs.<tab>` at the REPL?

**Comment by theogf** [comment]
But if we define `build_likelihood` in each sub-module, then they are completely separate functions right? So the user interface would change as well, as one would always need to call `LaplaceModule.build_objective` 

> I could imagine the usual multiple dispatch solution failing here if it's the case that there's lot of helper functions that are specific to each approximation, for example. e.g. _prior_kl in the SparseVariationalApproximation presumably won't get used in the Laplace approximation 🤷

I don't think I understand this point? You generally mean that the module space will be too polluted?

**Comment by willtebbutt** [comment]
> But if we define build_likelihood in each sub-module, then they are completely separate functions right? So the user interface would change as well, as one would always need to call LaplaceModule.build_objective

Sure. My understanding of @st-- 's point is to avoid putting anything the user would want to interact with in the submodules. Have I got that right?

> I don't think I understand this point? You generally mean that the module space will be too polluted?

Yes, that's the obvious advantage that I can see to using submodules. As I said alluded to above though, my prior uncertainty about the utility of making use of many submodules inside this package is large.

**Comment by st--** [comment]
To clarify, this is NOT about changing the API. End-users should stick to the symbols exported by ApproximateGPs. So you would still do `approx_lml(LaplaceApproximation(), ...)` or `approx_lml(SparseVariationalApproximation(), ...)`.

It's more about keeping utility functions and imports tidy - I think it is easier to follow code when it's clear where each bit comes from, and this is helped by qualified `using Package: name` imports if you only use a small part of some package. Submodules would allow us to make clear that e.g. some import is only used by Laplace approximation. It also makes it clearer what one package might be reusing from another package (e.g. EP -> SVA).

You can find this used in practice, for example, in [Pkg.jl](https://github.com/JuliaLang/Pkg.jl/tree/master/src). It just makes slightly stronger boundaries between different, mostly-independent aspects, better separation of concerns.

**Comment by st--** [comment]
@theogf
> But if we define build_likelihood in each sub-module, then they are completely separate functions right? So the user interface would change as well, as one would always need to call LaplaceModule.build_objective

Yes, that's right, and I think that's an advantage while we're trying to figure out what works. If it turned out that we could build a good common API for `build_objective`, for example, then of course this is something we could lift back up into the "main" package again. :)

@willtebbutt
> does using submodules gain us anything that name-mangling doesn't, beyond aesthetics when you type ApproximateGPs.<tab> at the REPL?

Not sure, but this is the main advantage for me - I really dislike tab completion with lots of entries - and of course we could alleviate that by always having the qualifier up front, `laplace_build_objective` etc., but separate modules seems a much cleaner way to me.

**Comment by devmotion** [comment]
> I think it is easier to follow code when it's clear where each bit comes from, and this is helped by qualified using Package: name imports if you only use a small part of some package.

I think it's even clearer if one only uses `using Package: Package` or equivalently `import Package` and qualifies all occurrences, but this comes at the cost of longer names, of course.

**Comment by st--** [comment]
Addressed by #96.
